---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard
---
  
```{r setup, include=FALSE}
library(flexdashboard)
library(data.table) 
library(dplyr)
library(ggplot2)
library(sp)
library(leaflet)
```

Column
-----------------------------------------------------------------------
  
### Mapa
  
```{r}

adequacao_rs <- fread("adequacao_rs.csv")

mapa_rs <- readRDS("MapaRSMunicipios.RDS")

base_mapa <- merge(mapa_rs, adequacao_rs, by="GEOCODIGO")

gradiente <- colorNumeric(palette = "YlOrRd", domain = base_mapa$ensino_fundamental)

base_mapa%>%
  leaflet() %>% 
  addProviderTiles(providers$OpenStreetMap)%>%
  addPolygons(weight = 1, color = "grey", fillColor = ~gradiente(base_mapa$ensino_fundamental), fillOpacity = 0.5,
              popup = paste0(base_mapa$cidade, "<br>", "Porcentagem: ", base_mapa$ensino_fundamental, "%"))%>%
  addLegend(position = "bottomright", pal = gradiente, values = ~ensino_fundamental, title="Legenda:")  

```

Column
-----------------------------------------------------------------------
  
### Gráfico 1
  
```{r}

banco_mundial_2019_2020 <- fread("banco_mundial_2019_2020.csv")

banco_mundial_2019_2020 <- mutate(banco_mundial_2019_2020, pib_per_capita=pib_dolares_precos_correntes/populacao)

ggplot(banco_mundial_2019_2020)+
  geom_point(aes(x=pib_per_capita, y=expectativa_de_vida_ao_nascer_homens, fill=continente, size=populacao), shape=21, color="black", alpha=0.7)+
  geom_smooth(aes(x=pib_per_capita, y=expectativa_de_vida_ao_nascer_homens), method="lm", se=FALSE, colour="black")+
  geom_text(data=subset(banco_mundial_2019_2020, pais=="Brasil"|pais=="China"|pais=="Índia"), aes(x=pib_per_capita, y=expectativa_de_vida_ao_nascer_homens, label=paste(codigo)), size=4, colour="black")+
  scale_x_log10(labels=function(x) format(x, scientific = FALSE))+
  scale_size_continuous(range = c(2, 10))+
  labs(y="Expectativa de vida ao nascer para os Homens", x="PIB per capita (base log)", fill="Legenda:", title="Correlação entre expectativa de vida ao nascer e PIB per capita")+
  guides(fill = guide_legend(override.aes = list(size=4)), size=FALSE)+
  theme(legend.position = "bottom")

```

### Gráfico 2

```{r}

pib <- fread("pib_trimestral_dessazonalizado_indice.csv")

pib$trimestre <- as.Date(pib$trimestre, format="%d/%m/%Y")

pib$positivo[pib$crescimento_pib>0] <- 1 
pib$positivo[pib$crescimento_pib<0] <- 0 
pib$positivo <- as.factor(pib$positivo)

pib_filtrado <- filter(pib, trimestre>=as.Date("01/01/2010", format="%d/%m/%Y"))

ggplot(pib_filtrado)+
  geom_col(data=subset(pib_filtrado, !is.na(crescimento_pib)), aes(x=trimestre, y=crescimento_pib*100, fill=positivo))+
  geom_line(aes(x=trimestre, y=pib), color="black", size=1)+
  scale_y_continuous(sec.axis = sec_axis(~ ./100, name = "Crescimento (%)"))+
  labs(x="Trimestre", y="Número índice", title="PIB trimestral dessazonalizado")+
  scale_x_date(date_breaks = "6 month", date_labels = "%m/%Y")+
  theme(axis.text.x = element_text(angle=90, hjust=1), legend.position = "none")+
  scale_fill_manual(values=c("red", "springgreen4"))+
  geom_hline(yintercept=0, linetype="dashed")

```
